version: '3.8'

services:
  tg_bot:
    build:
      context: ./bot
      dockerfile: Dockerfile_bot
    env_file:
      - .env
    depends_on:
      - db

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/code:ro
    env_file:
      - .env
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5434
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=electricity
    depends_on:
      - redis

  map:
    build:
      context: ./map
      dockerfile: Dockerfile
    expose:
      - 8001
    ports:
      - "8001:8001"
    depends_on:
      - web

volumes:
  postgres_data:
