version: '3.8'

services:
  tg_bot:
    build:
      context: ./bot
      dockerfile: Dockerfile_bot
    environment:
      - TG_BOT_TOKEN=7070344661:AAEWKc6drAOyQc5L3vBru-UO7a3bb3zx9-I
      - DATABASE_URL=postgresql+asyncpg://tg_bot:1111@db:5432/electricity

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/code:ro
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:1111@db:5432/electricity
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5434
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=electricity

volumes:
  postgres_data:
